Repository Team-groupHi/grouphi-mvp-fe, pull requests merged in 2024-10, with the labels that each got.

#15 지라 연동 테스트 & 깃 메세지 추가
  .github/workflows/create-jira-issue.yml
  .gitmessage.txt
Labels: 🔧개발 환경

#21 디자인 시스템 구축하기
  src/app/favicon.ico
  src/app/layout.tsx
  tailwind.config.ts
Labels: 🔧개발 환경

#22 GA4 연동
  .gitignore
  src/app/layout.tsx
Labels: ✨기능

#37 vitest "React is not defined" 오류 해결
  package.json
  vitest.config.ts
  yarn.lock
Labels: 🔧개발 환경, 🧪테스트

#44 세미콜론 설정 추가
  .eslintrc.json
  .prettierrc
  next.config.mjs
  postcss.config.mjs
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
  src/__tests__/setup.ts
  src/app/api/sentry-example-api/route.ts
  src/app/global-error.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/sentry-example-page/page.tsx
  src/instrumentation.ts
  tailwind.config.ts
  vitest.config.ts
Labels: 🔧개발 환경

#33 Button 컴포넌트 구현
  .eslintrc.json
  .gitmessage.txt
  components.json
  package.json
  src/components/Button/Button.test.tsx
  src/components/Button/Button.tsx
  src/components/Button/index.ts
  src/components/index.tsx
  src/lib/utils.ts
  tailwind.config.ts
  yarn.lock
Labels: ✨기능

#29 gameListCard 컴포넌트 구현
  src/components/GameListCard/GameListCard.test.tsx
  src/components/GameListCard/GameListCard.tsx
  src/components/GameListCard/index.tsx
  tailwind.config.ts
Labels: ✨기능

#45 디자인 시스템 1차 수정
  src/app/fonts/GeistMonoVF.woff
  src/app/fonts/GeistVF.woff
  src/app/fonts/PretendardVariable.woff2
  src/app/fonts/fonts.ts
  src/app/layout.tsx
  tailwind.config.ts
Labels: 🔧개발 환경
