Repository Team-groupHi/grouphi-mvp-fe, pull requests merged in 2024-12, with the labels that each got.

#66 Button 컴포넌트 variant 추가
  src/components/Button/Button.tsx
Labels: 🍜리뷰 3초컷, ✨기능

#71 디자인 시스템 폰트 토큰 추가
  tailwind.config.ts
Labels: 🍜리뷰 3초컷, 🔧개발 환경

#63 UserInfoCard 컴포넌트
  public/images/characters/blue.png
  public/images/characters/blue.webp
  public/images/characters/green.png
  public/images/characters/green.webp
  public/images/characters/mint.png
  public/images/characters/mint.webp
  public/images/characters/orange.png
  public/images/characters/orange.webp
  public/images/characters/pink.png
  public/images/characters/pink.webp
  public/images/characters/purple.png
  public/images/characters/purple.webp
  public/images/characters/red.png
  public/images/characters/red.webp
  public/images/characters/yellow.png
  public/images/characters/yellow.webp
  public/images/logos/favicon.ico
  public/images/logos/grouphi_logo.png
  public/images/logos/grouphi_logo_and_text.png
  public/images/logos/grouphi_logo_origin.png
  public/images/logos/grouphi_logo_text.png
  src/components/UserInfoCard/UserInfoCard.test.tsx
  src/components/UserInfoCard/UserInfoCard.tsx
  src/components/UserInfoCard/index.ts
  vercel.json
Labels: ✨기능

#61 채팅 컴포넌트
  src/components/Chatting/Chatting.test.tsx
  src/components/Chatting/Chatting.tsx
  src/components/Chatting/Item.tsx
  src/components/Chatting/index.ts
Labels: ✨기능

#53 모달 기능 구현
  src/app/layout.tsx
  src/components/BalanceGameQuestionCard/BalanceGameQuestionCard.test.tsx
  src/components/Modal/Modal.test.tsx
  src/components/Modal/ModalRenderer.tsx
  src/components/Modal/ModalShell.tsx
  src/components/Modal/index.ts
  src/components/ModalList/Modal1.tsx
  src/store/useModalStore.ts
Labels: ✨기능

#77 gameListCard 디자인 수정
  src/components/GameListCard/GameListCard.tsx
  src/components/index.tsx
  tailwind.config.ts
Labels: 🍜리뷰 3초컷, 💄디자인

#74 Slider 컴포넌트 구현
  package.json
  src/components/Slider/Slider.test.tsx
  src/components/Slider/Slider.tsx
  src/components/Slider/index.ts
  src/components/index.tsx
  yarn.lock
Labels: ✨기능

#69 대기실 페이지
  public/assets/dice.jpg
  src/app/balance-game/[roomId]/DUMMY.ts
  src/app/balance-game/[roomId]/page.tsx
  src/components/Chatting/Chatting.tsx
Labels: ✨기능
