Repository Team-groupHi/grouphi-mvp-fe, pull requests merged in 2025-03, with the labels that each got.

#143 Footer 컴포넌트 구현
  src/components/Footer/Footer.tsx
  src/components/Footer/index.ts
  src/components/HomeClient/HomeClient.tsx
  src/components/index.ts
Labels: 🍜리뷰 3초컷, ✨기능

#144 메인페이지(MainPage) 1차 수정 PR 반영
  src/app/layout.tsx
  src/hooks/useWebSocket.ts
Labels: 🍜리뷰 3초컷

#149 개발/배포 환경 분리에 따른 UI 조건부 출력
  src/app/balance-game/[roomId]/_component/PrevGame.tsx
  src/components/MainHeader/MainHeader.tsx
  src/components/Navigation/Navigation.tsx
  src/utils/env.ts
Labels: 🍜리뷰 3초컷, ✨기능

#153 Scroll 디자인 적용
  src/app/globals.css
Labels: 🍜리뷰 3초컷, 💄디자인

#156 디자인 시스템 컬러 코드 분리
  src/components/PieChart/PieChart.tsx
  src/components/ShootingStars/ShootingStars.tsx
  src/styles/theme.ts
  tailwind.config.ts
Labels: 🍜리뷰 3초컷, 💄디자인
