Repository Team-groupHi/grouphi-mvp-fe, pull requests merged in 2025-02, with the labels that each got.

#107 닉네임 모달 수정 1차
  src/components/ModalList/CreateUserNameModal.tsx
Labels: ✨기능

#112 UserInfoCard 방장 표시 기능
  public/images/crown.png
  src/app/balance-game/[roomId]/page.tsx
  src/components/UserInfoCard/UserInfoCard.tsx
  tailwind.config.ts
Labels: 🍜리뷰 3초컷, ✨기능

#115 깃허브 프로젝트 기반 브랜치 생성 룰 적용
  .github/ISSUE_TEMPLATE/issue-form.yml
  .github/workflows/create-branch.yml
Labels: 🔧개발 환경
