Repository Team-groupHi/grouphi-mvp-fe, pull requests merged in 2025-08, with the labels that each got.

#218 레이아웃 광고 영역 추가
  src/app/room/[roomId]/_component/PrevGame.tsx
  src/app/room/[roomId]/_component/UserList.tsx
  src/app/room/[roomId]/_component/WaitingRoom.tsx
  src/components/AdBanner/AdBanner.tsx
  src/components/AdBanner/index.ts
  src/components/BalanceGame/BalanceGameControl.tsx
  src/components/BalanceGame/BalanceGameProgress.tsx
  src/components/Chatting/Chatting.tsx
  src/components/Footer/Footer.tsx
  src/components/HomeClient/HomeClient.tsx
  src/components/MainHeader/MainHeader.tsx
  src/components/PartialResultChart/PartialResultChart.tsx
  src/components/PieChart/PieChart.tsx
  src/components/UserInfoCard/UserInfoCard.tsx
  src/components/index.ts
  tailwind.config.ts
Labels: 💄디자인

#213 최종결과 QA
  src/components/FinalResultChart/ResultRow.tsx
Labels: ✨기능, ♻️리팩토링, 💄디자인

#220 소켓 연결 setTimeout 삭제 및 구조 변경
  src/app/room/[roomId]/_component/WaitingRoom.tsx
  src/hooks/useWebSocket.ts
Labels: 🍜리뷰 3초컷, ♻️리팩토링
