Repository Team-groupHi/grouphi-mvp-fe, pull requests merged in 2025-07, with the labels that each got.

#187 2506 QA 테스트 수정
  src/app/about/page.tsx
  src/app/layout.tsx
  src/app/room/[roomId]/_component/GamePanel.tsx
  src/app/room/[roomId]/_component/UserList.tsx
  src/app/room/[roomId]/_component/WaitingRoom.tsx
  src/components/ErrorBoundary/ErrorFallback.tsx
  src/components/Footer/Footer.tsx
  src/components/GameListCard/GameListCard.test.tsx
  src/components/HomeClient/HomeClient.tsx
  src/components/MainHeader/MainHeader.tsx
  src/components/Navigation/Navigation.tsx
  src/components/QnaGame/QnaGameFinalResult.tsx
  src/hooks/useWebSocket.ts
  src/store/useRoomStore.ts
Labels: 🐛버그

#190 Scoreboard 컴포넌트 구현
  src/app/room/_card-game/_component/Scoreboard.tsx
  src/styles/theme.ts
Labels: ✨기능

#196 Timer 로직 변경
  src/components/BalanceGame/BalanceGameProgress.tsx
  src/components/Timer/Timer.tsx
  src/constants/api.ts
  src/hooks/useSSE.ts
  src/types/websocket.ts
Labels: ✨기능, ♻️리팩토링

#212 긴 링크 채팅창 넘침 이슈 수정
  src/components/Chatting/Item.tsx
Labels: 🍜리뷰 3초컷, 🐛버그, 💄디자인
