Repository Team-groupHi/grouphi-mvp-fe, pull requests merged in 2025-01, with the labels that each got.

#82 Timer 컴포넌트
  src/components/Timer/Timer.test.tsx
  src/components/Timer/Timer.tsx
  src/components/Timer/index.ts
Labels: ✨기능

#79 Spinner 컴포넌트 구현
  package.json
  public/loading/groupHi_Spinner_background.json
  public/loading/groupHi_Spinner_item.json
  src/components/Spinner/Spinner.tsx
  src/components/Spinner/index.ts
  src/components/index.tsx
  tailwind.config.ts
  vercel.json
  yarn.lock
Labels: ✨기능, 🔧개발 환경

#83 메인페이지(MainPage) 구현
  package.json
  public/images/logos/grouphi_logo_text_white.png
  src/app/about/page.tsx
  src/app/api/axiosErrorHandler.ts
  src/app/api/axiosInstance.ts
  src/app/balance-game/[roomId]/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/GameListCard/GameListCard.tsx
  src/components/HomeClient/HomeClient.tsx
  src/components/HomeClient/index.ts
  src/components/Logo/Logo.tsx
  src/components/Logo/index.ts
  src/components/MainHeader/MainHeader.tsx
  src/components/MainHeader/index.ts
  src/components/Modal/index.ts
  src/components/ModalList/CreateBalanceGameModal.tsx
  src/components/Navigation/Navigation.tsx
  src/components/Navigation/index.ts
  src/components/ShootingStars/ShootingStars.tsx
  src/components/ShootingStars/StarsBackground.tsx
  src/components/ShootingStars/index.ts
  src/components/index.tsx
  src/constants/api.ts
  src/constants/form.ts
  src/constants/router.ts
  src/services/games.ts
  src/services/rooms.ts
  src/store/useRoomStore.ts
  src/types/api.ts
  src/utils/providers.tsx
  yarn.lock
Labels: ✨기능

#93 [핫픽스] src/components/balanceGameQuestionCard directory 제거
  src/components/balanceGameQuestionCard/index.tsx
Labels: 🚨긴급 핫픽스

#84 WebSocket 기본 로직 구현
  package.json
  src/constants/websocket.ts
  src/hooks/useWebSocket.ts
  src/types/index.ts
  yarn.lock
Labels: ✨기능

#89 대기실 페이지 소켓 및 API 연결 1차
  src/app/balance-game/[roomId]/DUMMY.ts
  src/app/balance-game/[roomId]/PrevGame.tsx
  src/app/balance-game/[roomId]/page.tsx
  src/components/Chatting/Chatting.tsx
  src/components/Chatting/Item.tsx
  src/components/ModalList/CreateUserNameModal.tsx
  src/components/UserInfoCard/UserInfoCard.tsx
  src/components/index.tsx
  src/constants/api.ts
  src/constants/querykey.ts
  src/hooks/useFetchRoomDetail.ts
  src/hooks/useWebSocket.ts
  src/services/rooms.ts
  src/store/useRoomStore.ts
  src/types/api.ts
  yarn.lock
Labels: ✨기능

#92 최종 결과 차트 이미지로 공유하기 구현
  package.json
  src/components/FinalResultChart/Bar.tsx
  src/components/FinalResultChart/FinalResultChart.tsx
  src/components/Modal/ModalRenderer.tsx
  src/components/ModalList/SaveImageModal.tsx
  tailwind.config.ts
  yarn.lock
Labels: ✨기능, ♻️리팩토링

#99 랜덤 닉네임 생성 기능 구현
  public/data/nickname.json
  src/app/layout.tsx
  src/components/InitialNickname/InitialNickname.tsx
  src/components/InitialNickname/index.ts
  src/components/index.tsx
  src/constants/storage.ts
  src/hooks/useLocalStorage.ts
  src/utils/randomNickname.ts
  vercel.json
Labels: ✨기능

#100 부분 결과 컴포넌트 구현
  src/components/PartialResultChart/PartialResultChart.tsx
  src/components/PartialResultChart/index.ts
  src/components/PieChart/index.ts
  src/components/index.tsx
  tailwind.config.ts
Labels: ✨기능

#101 밸런스 게임 진행 컴포넌트
  package.json
  src/app/balance-game/[roomId]/PrevGame.tsx
  src/app/balance-game/[roomId]/page.tsx
  src/components/BalanceGameProgress/BalanceGameProgress.tsx
  src/components/BalanceGameProgress/index.ts
  src/components/ModalList/CreateBalanceGameModal.tsx
  src/components/Timer/Timer.tsx
  src/hooks/useWebSocket.ts
  src/store/useBalanceGameStore.ts
  src/store/useRoomStore.ts
  src/types/api.ts
  yarn.lock
Labels: ✨기능

#103 밸런스 게임 비즈니스 로직 병합
  src/app/balance-game/[roomId]/PrevGame.tsx
  src/app/balance-game/[roomId]/page.tsx
  src/components/BalanceGameProgress/BalanceGameProgress.tsx
  src/components/Chatting/Chatting.tsx
  src/components/FinalResultChart/Bar.tsx
  src/components/GameListCard/GameListCard.tsx
  src/components/HomeClient/HomeClient.tsx
  src/components/InitialNickname/InitialNickname.tsx
  src/components/MainHeader/MainHeader.tsx
  src/components/ModalList/CreateBalanceGameModal.tsx
  src/components/ModalList/CreateUserNameModal.tsx
  src/components/PartialResultChart/PartialResultChart.tsx
  src/components/ShootingStars/ShootingStars.tsx
  src/components/ShootingStars/StarsBackground.tsx
  src/constants/api.ts
  src/constants/websocket.ts
  src/hooks/useLocalStorage.ts
  src/hooks/useWebSocket.ts
  src/services/balanceGames.ts
  src/store/useRoomStore.ts
Labels: ✨기능, 🐛버그, ♻️리팩토링
