Repository Team-groupHi/grouphi-mvp-fe, pull requests merged in 2025-04, with the labels that each got.

#150 대기실 페이지 최적화 및 에러 바운더리 적용
  .eslintrc.json
  src/app/api/axiosErrorHandler.ts
  src/app/balance-game/[roomId]/_component/GamePanel.tsx
  src/app/balance-game/[roomId]/_component/PrevGame.tsx
  src/app/balance-game/[roomId]/_component/UserList.tsx
  src/app/balance-game/[roomId]/_component/WaitingRoom.tsx
  src/app/balance-game/[roomId]/page.tsx
  src/app/sentry-example-page/page.tsx
  src/components/BalanceGameProgress/BalanceGameProgress.tsx
  src/components/Chatting/Chatting.test.tsx
  src/components/ErrorBoundary/ErrorBoundary.tsx
  src/components/ErrorBoundary/ErrorFallback.tsx
  src/components/ErrorBoundary/ErrorHandlingWrapper.tsx
  src/components/FinalResultChart/FinalResultChart.test.tsx
  src/components/HomeClient/GameListCarousel.tsx
  src/components/HomeClient/HomeClient.tsx
  src/components/Logo/Logo.tsx
  src/components/ModalList/Modal1.tsx
  src/components/PartialResultChart/PartialResultChart.tsx
  src/components/Spinner/Spinner.tsx
  src/components/UserInfoCard/UserInfoCard.tsx
  src/constants/api.ts
  src/constants/querykey.ts
  src/hooks/useFetchRoomDetail.ts
  src/hooks/useThrottleHandlers.ts
  src/hooks/useWebSocket.ts
  src/services/balanceGames.ts
  src/services/games.ts
  src/services/rooms.ts
  src/store/useBalanceGameStore.ts
  src/types/api.ts
  src/types/axios.d.ts
  src/types/index.ts
  src/types/websocket.ts
  src/utils/throttle.ts
  yarn.lock
Labels: ✨기능, ♻️리팩토링

#146 검색 엔진 최적화(SEO)
  public/images/opengraph-image.png
  public/images/twitter-image.png
  src/app/icons/apple-icon.png
  src/app/icons/icon.svg
  src/app/layout.tsx
  src/app/robots.ts
  src/app/sitemap.ts
  src/constants/metadata.ts
Labels: ♻️리팩토링

#159 QnA 게임 아바타 상태 표시 컴포넌트 추가
  src/components/QnAGameProgress/index.ts
  src/components/QnaGameProgress/QnaGameAvatarStatus.tsx
  src/components/QnaGameProgress/index.ts
  src/components/index.ts
Labels: 🍜리뷰 3초컷, ✨기능

#164 에러 코드 변경 사항 적용
  src/types/index.ts
Labels: 🍜리뷰 3초컷
